# Generated by Django 5.1.2 on 2024-11-03 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0004_rent_alter_deposit_date_submit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation_request',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_core.rooms'),
        ),
    ]
