# Generated by Django 5.1.2 on 2024-11-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0005_alter_accomodation_request_approved_alter_rent_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
